name: OSSPH Website:Production

on: 
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: OSSPH Website to production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use ossph-org
          firebase target:clear hosting prod
          firebase target:apply hosting prod ossph-org
          firebase deploy --only hosting:prod -P ossph-org
